### ISSUE TITLE
Can you explain:  ​/controller​/button​/release​/{button_name}

### ISSUE THREAD

**Issue by MadeSimpleWorkshop** [choss/joycontrol_rest_api#5]
Maybe an example on how would you execute this in joycontrol?

**Comment by choss** [comment]
​/controller​/button​/press/{button_name}: sends a pressed state of a button (like putting your thumb on the button and keeping it there)

​/controller​/button​/release​/{button_name}: sends a release signal of a button (now you lift your thumb)

The swagger docs have a try me out functions, where you can get the curl commands

**Comment by MadeSimpleWorkshop** [comment]
I was digging into both your code and joycontrols code to understand the release better.   I think part of my confusion is with the cmd documentation below on joycontrol.   There's no mention of capture or release, but in the code they are pausing.  It looks like your accessing the deeper logic also and not the abstracted button commands.  The button commands actual -> Press -> Wait -> Release buttons.  

Just checking if I understood that correctly and how with button commands would I hold down a button?

Button commands:
b, home, left, r_stick, r, zl, down, x, capture, y, l, right, up, zr, minus, plus, l_stick, a

Commands:

stick - Command to set stick positions.
:param side: 'l', 'left' for left control stick; 'r', 'right' for right control stick
:param direction: 'center', 'up', 'down', 'left', 'right';
                  'h', 'horizontal' or 'v', 'vertical' to set the value directly to the "value" argument
:param value: horizontal or vertical value
        

test_buttons - Navigates to the "Test Controller Buttons" menu and presses all buttons.
            

mash - Mash a specified button at a set interval

Usage:
    mash <button> <interval>
            

nfc - Sets nfc content

Usage:
    nfc <file_name>          Set controller state NFC content to file
    nfc remove               Remove NFC content from controller state
            
Commands can be chained using "&&"

**Comment by choss** [comment]
Yes I am ignoring all that CLI stuff and am using the controller_state and protocol of joycontrol directly. I basically re-implemented the CLI part as a rest service.

Valid buttons for press, release and tap are: y, x, b, a, r, zr, minus, plus, r_stick, l_stick, home, capture, down, up, right, left, l, zl, sr, sl (as described in the api and not all buttons for all controllers. Pro controller doesn't have sr/slr)

Valid sticks are:  l_stick, r_stick
Valid axis are: x_axis, y_axis (instead of h and v)
Valid axis values are between 0 and 4095

The openAPI doc should describe those values on opening up the rest api with a browser under http://\<ip\>:8000/docs or http://\<ip\>:8000/redoc

A button is held down until the release command for this button is issued, as far as I understand joycontrols code.

**Comment by MadeSimpleWorkshop** [comment]
Really appreciate the time in explaining,  helps me understand expected results for better testing.
